# http://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
sudo: required
dist: trusty
services:
  - docker
language: python
env:
  global:
    - PATH="/usr/bin:$PATH"
services:
  #- docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  #- ansible-galaxy install -r requirements.yml

install:
  #- pip install molecule
  - sudo pip install ansible
  - sudo pip install molecule==1.25.0
  - sudo pip install docker

script:
  - molecule create
  - molecule converge
  - molecule syntax
  - molecule idempotence

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
