# http://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
sudo: required
# dist: trusty
services:
  - docker
language: python
env:
  global:
    - PATH="/usr/bin:$PATH"

install:
  - sudo apt-get install -y python-pip libssl-dev libffi-dev
  - sudo pip install molecule
  - sudo pip install ansible
  - sudo pip install docker-py
  - ansible-galaxy install -r requirements.yml

script:
  - molecule --debug create
  - molecule converge
  - molecule syntax
  #- molecule idempotence

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
