---
# file defaults/bui-celery.yml

- name: install Supervisor
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ burp_ui_celery_dependencies }}"

- name: create burp ui folder
  file:
    path: /var/spool/burpui
    state: directory

- name: configure bui-celery
  template:
    src: bui-celery.conf_supervisor.j2
    dest: "{{ supervisoretc_dir }}/bui-celery.{{ supervisor_ext }}"
  notify: restart bui-celery

- name: configure supervisor logrotate
  template:
    src: supervisor_logrotate.j2
    dest: /etc/logrotate.d/supervisor

- name: ensure supervisor is started
  service:
    name: "{{ supervisor_service }}"
    state: started
    sleep: 4

- name: ensure supervisor is restarted
  service:
    name: "{{ supervisor_service }}"
    state: restarted
    sleep: 4
  changed_when: false

- name: ensure supervisor is enabled
  service:
    name: "{{ supervisor_service }}"
    enabled: yes
