---

- name: Upgrade database schema
  shell: bui-manage -c /etc/burp/burpui.cfg db upgrade

# TODO: Change user to burpui
# TODO: check other way to run it without breaking ansible task
#- name: Upgrade celery beat
#  shell: bui-celery -c /etc/burp/burpui.cfg -- --beat
#  environment: 
#    C_FORCE_ROOT: "True"


# Restart services
- meta: flush_handlers
