---
# https://github.com/ziirish/burp-ui/blob/master/docs/gunicorn.rst

- name: gunicorn | directory /var/log/gunicorn 
  file: 
    path: '/var/log/gunicorn'
    state: directory

- block:

  - name: gunicorn | remove gunicorn example files
    file:
      path: "/etc/gunicorn.d/{{ item }}"
      state: absent
    with_items:
      - django.example
      - wsgi.example

  - name: gunicorn | Debian configure gunicorn server
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: "burpui_gunicorn.j2", dest: "/etc/gunicorn.d/burpui" }
      - { src: "gunicorn_logrotate.j2", dest: "/etc/logrotate.d/gunicorn" }
    notify: restart burpui services
  
  when: ansible_os_family == 'Debian' and not gunicorn_systemd_service

- block: 

  - name: gunicorn | Uninstall gunicorn from debian package
    package:
      name: gunicorn
      state: absent
    when: ansible_os_family == 'Debian'

  - name: gunicorn | Install gunicorn from pip for Debian family
    pip:
      name: gunicorn>=19.7.1
      state: present
      executable: "{{ python_pip_executable }}"
    when: ansible_os_family == 'Debian'

  - name: gunicorn | copy burpui_gunicorn.py file
    template:
      mode: 0755
      src: burpui_gunicorn.py.j2
      dest: /etc/burp/burpui_gunicorn.py
      owner: root
      group: root
  
  - name: gunicorn | setup gunicorn.service systemd
    template:
      src: gunicorn_systemd.j2
      dest: /etc/systemd/system/gunicorn.service
      mode: 0755
      owner: root
      group: root

  when: ansible_os_family == 'RedHat' or gunicorn_systemd_service
