---
# file: tasks/main.yml
# https://git.ziirish.me/ziirish/burp-ui/blob/master/docker/docker-burpui/assets/setup/install

- include: multi_os.yml

- name: install role packages
  package:
    name: "{{ burpui_packages| join(',') }}"
    state: latest

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ burpui_pip_present }}"

- name: upgrade pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ burpui_pip_latest }}"

- name: create burp folder
  file:
    path: /etc/burp
    state: directory

- name: remove gunicorn example files
  file:
    path: "/etc/gunicorn.d/{{ item }}"
    state: absent
  with_items:
    - django.example
    - wsgi.example

- name: configure burpui server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "burpui.cfg.j2", dest: "/etc/burp/burpui.cfg" }
    - { src: "burpui_gunicorn.j2", dest: "/etc/gunicorn.d/burpui" }
    - { src: "burpui_site.j2", dest: "/etc/nginx/sites-available/burpui" }
    - { src: "gunicorn_logrotate.j2", dest: "/etc/logrotate.d/gunicorn" }
  notify: restart burpui services

- name: enable nginx site
  file:
    src: "/etc/nginx/sites-available/burpui"
    dest: "/etc/nginx/sites-enabled/burpui"
    state: link

- name: ensure services are enabled
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - gunicorn
    - nginx

- include: bui-celery.yml
  when: burpui_production_celery