---
# file: tasks/main.yml
# https://git.ziirish.me/ziirish/burp-ui/blob/master/docker/docker-burpui/assets/setup/install

- include_tasks: multi_os.yml

- include_tasks: requirements.yml

- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: set gunicorn_systemd_service true for Ubuntu 16.04 and newer
  set_fact: 
    gunicorn_systemd_service: True
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= 16

- name: change burpui_packages when gunicorn_systemd_service true and ansible_os_family Debian
  set_fact:
    burpui_packages:
      - redis-server
      - nginx
  when: ansible_os_family == 'Debian' and gunicorn_systemd_service

- name: Install redhat-rpm-config when running Fedora
  package:
    name: redhat-rpm-config
    state: present
  when: ansible_distribution == 'Fedora'

- name: check only if burpui is installed
  pip:
    name: "{{ burpui_pip_burpui }}"
    state: present
    executable: "{{ python_pip_executable }}"
  register: burpui_installed_check
  check_mode: yes

- name: install role packages
  package:
    name: "{{ burpui_packages| join(',') }}"
    state: present

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: "{{ python_pip_executable }}"
  with_items: "{{ burpui_pip_present }}"

- name: Uninstall burpui pip2 packages when using pip3 as pip executable
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
    executable: "pip2"
  when: python_pip_executable == "pip3"  
  with_items: "{{ burpui_pip_packages }}"

- name: Install pip packages by version
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
    executable: "{{ python_pip_executable }}"
  with_items: "{{ burpui_pip_packages }}"
  register: bui_pip_install
  notify: restart burpui services

- name: create burp folder
  file:
    path: /etc/burp
    state: directory

- name: configure burpui server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "burpui.cfg.j2", dest: "/etc/burp/burpui.cfg" }
    - { src: "burpui_site.j2", dest: "{{ burpui_nginx_config_path }}" }
  notify: restart burpui services

- name: enable nginx site
  file:
    src: "{{ burpui_nginx_config_path }}"
    dest: "/etc/nginx/sites-enabled/burpui"
    state: link
  when: ansible_os_family == 'Debian'

- name: fix httproxy issue in ngnix
  lineinfile:
    dest: "/etc/nginx/fastcgi_params"
    regexp: "{{ item.src }}"
    line: "{{ item.value }}"
  with_items:
    - { src: 'fastcgi_param HTTP_PROXY "";' , value: 'fastcgi_param HTTP_PROXY "";' }

# include tasks for gunicorn specific
- include_tasks: gunicorn.yml

- include_tasks: bui-celery.yml
  when: burpui_production_celery

# This is prepared for next 0.5.0 version
- include_tasks: bui-upgrade.yml
  when: bui_pip_install.changed and not burpui_installed_check.changed

- name: ensure services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - gunicorn
    - nginx
    - "{{ redis_service }}"
