---

- name: pip2 | check only if burpui is installed
  pip:
    name: "{{ burpui_pip_burpui }}"
    state: present
    executable: "{{ python3_pip }}"
  register: burpui_installed_check
  check_mode: yes

- name: Uninstall burpui pip2 packages when using pip3 as pip executable
  pip:
    name: "{{ item.name }}"
    state: absent
    version: "{{ item.version}}"
    executable: "pip2"
  with_items: "{{ burpui_pip_packages }}"

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: "{{ python3_pip }}"
  with_items: "{{ burpui_pip_present }}"

- name: Install pip packages by version
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
    executable: "{{ python3_pip }}"
  with_items: "{{ burpui_pip_packages }}"
  register: bui_pip_install
  notify: restart burpui services
