---
# file: tasks/requirements.yml 

- name: ensure cache for apt is updated
  apt:
    update_cache: yes
    cache_valid_time: 43200
  changed_when: false
  when: ansible_os_family == 'Debian'
  
- name: install required system packages
  package:
    name: "{{ burpui_system_requirements | join(',') }}"
    state: present

# workaround for ubuntu 14.04 with missing pip3 executable
- block:
    
    - name: stat to see if pip3 executable is present
      stat:
        path: '/usr/bin/pip3'
      register: pip3_executable_stat
    
    - name: Absent python3-pip if /usr/bin/pip3 is not present
      package:
        name: 'python3-pip'
        state: absent
      when: not pip3_executable_stat.stat.exists
  
  when: ansible_distribution_release == 'trusty'

- name: install burpui package requirements for python3
  package:
    name: "{{ burpui_py3_packages| join(',') }}"
    state: present
  when: python_pip_executable == "pip3"
