---
# file: tasks/requirements.yml 

- name: ensure cache for apt is updated
  apt:
    update_cache: yes
    cache_valid_time: 43200
  changed_when: false
  when: ansible_os_family == 'Debian'
  
- name: install required system packages
  package:
    name: "{{ burpui_system_requirements | join(',') }}"
    state: present
  when: python_pip_executable != "pip3"

- name: install burpui package requirements for python3
  package:
    name: "{{ burpui_py3_packages| join(',') }}"
    state: present
  when: python_pip_executable == "pip3"

- name: install role packages
  package:
    name: "{{ burpui_packages| join(',') }}"
    state: present
