---

# Restart services if required
- meta: flush_handlers

- name: test if burpui gunircorn site about is ok
  get_url:
    url: http://localhost:{{ burpui_global_port }}/about
    dest: /tmp/test_burpui_about_gunicorn
    timeout: 30
  changed_when: false

- name: test if burpui get about is ok
  get_url:
    url: http://localhost:{{ burpui_nginx_port }}/about
    dest: /tmp/test_burpui_about_nginx
    timeout: 30
  changed_when: false
