---
# file: handlers/main.yml

- name: restart burpui services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - gunicorn
    - nginx

- name: restart bui-celery
  supervisorctl:
    name: bui-celery
    state: restarted