---
# file: handlers/main.yml

- name: restart burpui services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - gunicorn
    - nginx
  #when: ansible_os_family == 'Debian'
  notify: wait 10s

- name: restart bui-celery
  supervisorctl:
    name: bui-celery
    state: restarted

- name: wait 10s
  wait_for: timeout=10
  delegate_to: localhost
  become: no
