---
- name: Converge
  hosts: all
  vars:
    burpui_standalone: True
    burpui_use_dev: False
  roles:
    # - role: coffeeitworks.burp2_server
    - role: ansible_burpui_server
      tags:
        - burpui-server
